// This file is automatically generated.
#include "cssysdef.h"

struct _Bind_docconv_static_plugins
{
  _Bind_docconv_static_plugins ();
};
namespace { _Bind_docconv_static_plugins bind_docconv_static_plugins; }

