// This file is automatically generated.
#include "cssysdef.h"

struct _Bind_lighter2_static_plugins
{
  _Bind_lighter2_static_plugins ();
};
namespace { _Bind_lighter2_static_plugins bind_lighter2_static_plugins; }

