// This file is automatically generated.
#include "cssysdef.h"

struct _Bind_walktest_static_plugins
{
  _Bind_walktest_static_plugins ();
};
namespace { _Bind_walktest_static_plugins bind_walktest_static_plugins; }

