// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_blobs[] =
"<?xml version=\"1.0\"?>"
"<!-- blobs.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.utilities.blobs</name>"
"        <implementation>csBlobManager</implementation>"
"        <description>Blob Manager</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csBlobManager_FACTORY_REGISTER_DEFINED 
  #define csBlobManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csBlobManager) 
  #endif

class blobs
{
SCF_REGISTER_STATIC_LIBRARY(blobs,metainfo_blobs)
  #ifndef csBlobManager_FACTORY_REGISTERED 
  #define csBlobManager_FACTORY_REGISTERED 
    csBlobManager_StaticInit csBlobManager_static_init__; 
  #endif
public:
 blobs();
};
blobs::blobs() {}

}
