// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_bindoc[] =
"<?xml version=\"1.0\"?>"
"<!-- bindoc.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.documentsystem.binary</name>"
"        <implementation>csBinaryDocumentSystem</implementation>"
"        <description>Binary document system</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csBinaryDocumentSystem_FACTORY_REGISTER_DEFINED 
  #define csBinaryDocumentSystem_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csBinaryDocumentSystem) 
  #endif

class bindoc
{
SCF_REGISTER_STATIC_LIBRARY(bindoc,metainfo_bindoc)
  #ifndef csBinaryDocumentSystem_FACTORY_REGISTERED 
  #define csBinaryDocumentSystem_FACTORY_REGISTERED 
    csBinaryDocumentSystem_StaticInit csBinaryDocumentSystem_static_init__; 
  #endif
public:
 bindoc();
};
bindoc::bindoc() {}

}
