// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_bodymeshldr[] =
"<?xml version=\"1.0\"?>"
"<!-- bodymeshldr.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.loader.animesh.body</name>"
"        <implementation>BodyMeshLoader</implementation>"
"        <description>Crystal Space loader of the physical description of an animated mesh</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef BodyMeshLoader_FACTORY_REGISTER_DEFINED 
  #define BodyMeshLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(BodyMeshLoader) 
  #endif

class bodymeshldr
{
SCF_REGISTER_STATIC_LIBRARY(bodymeshldr,metainfo_bodymeshldr)
  #ifndef BodyMeshLoader_FACTORY_REGISTERED 
  #define BodyMeshLoader_FACTORY_REGISTERED 
    BodyMeshLoader_StaticInit BodyMeshLoader_static_init__; 
  #endif
public:
 bodymeshldr();
};
bodymeshldr::bodymeshldr() {}

}
