// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_bullet[] =
"<?xml version=\"1.0\"?>"
"<!-- bullet.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.dynamics.bullet</name>"
"        <implementation>csBulletDynamics</implementation>"
"        <description>Bullet physics</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csBulletDynamics_FACTORY_REGISTER_DEFINED 
  #define csBulletDynamics_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csBulletDynamics) 
  #endif

class bullet
{
SCF_REGISTER_STATIC_LIBRARY(bullet,metainfo_bullet)
  #ifndef csBulletDynamics_FACTORY_REGISTERED 
  #define csBulletDynamics_FACTORY_REGISTERED 
    csBulletDynamics_StaticInit csBulletDynamics_static_init__; 
  #endif
public:
 bullet();
};
bullet::bullet() {}

}
