// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_bullet2[] =
"<?xml version=\"1.0\"?>"
"<!-- bullet2.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.physics.bullet2</name>"
"        <implementation>csBulletSystem</implementation>"
"        <description>Bullet collision and physics</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csBulletSystem_FACTORY_REGISTER_DEFINED 
  #define csBulletSystem_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csBulletSystem) 
  #endif

class bullet2
{
SCF_REGISTER_STATIC_LIBRARY(bullet2,metainfo_bullet2)
  #ifndef csBulletSystem_FACTORY_REGISTERED 
  #define csBulletSystem_FACTORY_REGISTERED 
    csBulletSystem_StaticInit csBulletSystem_static_init__; 
  #endif
public:
 bullet2();
};
bullet2::bullet2() {}

}
