// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_bodymesh[] =
"<?xml version=\"1.0\"?>"
"<!-- bodymesh.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.animesh.body</name>"
"        <implementation>BodyManager</implementation>"
"        <description>Crystal Space Physical Description of an Animated Mesh</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef BodyManager_FACTORY_REGISTER_DEFINED 
  #define BodyManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(BodyManager) 
  #endif

class bodymesh
{
SCF_REGISTER_STATIC_LIBRARY(bodymesh,metainfo_bodymesh)
  #ifndef BodyManager_FACTORY_REGISTERED 
  #define BodyManager_FACTORY_REGISTERED 
    BodyManager_StaticInit BodyManager_static_init__; 
  #endif
public:
 bodymesh();
};
bodymesh::bodymesh() {}

}
