// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_cssynldr[] =
"<?xml version=\"1.0\"?>"
"<!-- cssynldr.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.syntax.loader.service.text</name>"
"        <implementation>csTextSyntaxService</implementation>"
"        <description>Crystal Space loader services for textual CS syntax</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csTextSyntaxService_FACTORY_REGISTER_DEFINED 
  #define csTextSyntaxService_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csTextSyntaxService) 
  #endif

class cssynldr
{
SCF_REGISTER_STATIC_LIBRARY(cssynldr,metainfo_cssynldr)
  #ifndef csTextSyntaxService_FACTORY_REGISTERED 
  #define csTextSyntaxService_FACTORY_REGISTERED 
    csTextSyntaxService_StaticInit csTextSyntaxService_static_init__; 
  #endif
public:
 cssynldr();
};
cssynldr::cssynldr() {}

}
