// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_colladaconvertor[] =
"<?xml version=\"1.0\"?>"
"<!-- colladaconvertor.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.utilities.colladaconvertor</name>"
"        <implementation>csColladaConvertor</implementation>"
"        <description>Crystal Space COLLADA Conversion System</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>";
  #ifndef csColladaConvertor_FACTORY_REGISTER_DEFINED 
  #define csColladaConvertor_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csColladaConvertor) 
  #endif

class colladaconvertor
{
SCF_REGISTER_STATIC_LIBRARY(colladaconvertor,metainfo_colladaconvertor)
  #ifndef csColladaConvertor_FACTORY_REGISTERED 
  #define csColladaConvertor_FACTORY_REGISTERED 
    csColladaConvertor_StaticInit csColladaConvertor_static_init__; 
  #endif
public:
 colladaconvertor();
};
colladaconvertor::colladaconvertor() {}

}
