// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_csjpgimg[] =
"<?xml version=\"1.0\"?>"
"<!-- csjpgimg.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.graphic.image.io.jpg</name>"
"        <implementation>csJPGImageIO</implementation>"
"        <description>CrystalSpace JPG image format I/O plugin</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csJPGImageIO_FACTORY_REGISTER_DEFINED 
  #define csJPGImageIO_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csJPGImageIO) 
  #endif

class csjpgimg
{
SCF_REGISTER_STATIC_LIBRARY(csjpgimg,metainfo_csjpgimg)
  #ifndef csJPGImageIO_FACTORY_REGISTERED 
  #define csJPGImageIO_FACTORY_REGISTERED 
    csJPGImageIO_StaticInit csJPGImageIO_static_init__; 
  #endif
public:
 csjpgimg();
};
csjpgimg::csjpgimg() {}

}
