// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_cspngimg[] =
"<?xml version=\"1.0\"?>"
"<!-- cspngimg.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.graphic.image.io.png</name>"
"        <implementation>csPNGImageIO</implementation>"
"        <description>CrystalSpace PNG image format I/O plugin</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csPNGImageIO_FACTORY_REGISTER_DEFINED 
  #define csPNGImageIO_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csPNGImageIO) 
  #endif

class cspngimg
{
SCF_REGISTER_STATIC_LIBRARY(cspngimg,metainfo_cspngimg)
  #ifndef csPNGImageIO_FACTORY_REGISTERED 
  #define csPNGImageIO_FACTORY_REGISTERED 
    csPNGImageIO_StaticInit csPNGImageIO_static_init__; 
  #endif
public:
 cspngimg();
};
cspngimg::cspngimg() {}

}
