// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_csfont[] =
"<?xml version=\"1.0\"?>"
"<!-- csfont.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.font.server.default</name>"
"        <implementation>csDefaultFontServer</implementation>"
"        <description>CrystalSpace default font server</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csDefaultFontServer_FACTORY_REGISTER_DEFINED 
  #define csDefaultFontServer_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csDefaultFontServer) 
  #endif

class csfont
{
SCF_REGISTER_STATIC_LIBRARY(csfont,metainfo_csfont)
  #ifndef csDefaultFontServer_FACTORY_REGISTERED 
  #define csDefaultFontServer_FACTORY_REGISTERED 
    csDefaultFontServer_StaticInit csDefaultFontServer_static_init__; 
  #endif
public:
 csfont();
};
csfont::csfont() {}

}
