// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_cameramanager[] =
"<?xml version=\"1.0\"?>"
"<!-- cameramanager.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.utilities.cameramanager</name>"
"        <implementation>CameraManager</implementation>"
"        <description>Camera motion manager</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef CameraManager_FACTORY_REGISTER_DEFINED 
  #define CameraManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(CameraManager) 
  #endif

class cameramanager
{
SCF_REGISTER_STATIC_LIBRARY(cameramanager,metainfo_cameramanager)
  #ifndef CameraManager_FACTORY_REGISTERED 
  #define CameraManager_FACTORY_REGISTERED 
    CameraManager_StaticInit CameraManager_static_init__; 
  #endif
public:
 cameramanager();
};
cameramanager::cameramanager() {}

}
