// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_decal[] =
"<?xml version=\"1.0\"?>"
"<!-- decal.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.decal.manager</name>"
"        <implementation>csDecalManager</implementation>"
"        <description>Decal support</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csDecalManager_FACTORY_REGISTER_DEFINED 
  #define csDecalManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csDecalManager) 
  #endif

class decal
{
SCF_REGISTER_STATIC_LIBRARY(decal,metainfo_decal)
  #ifndef csDecalManager_FACTORY_REGISTERED 
  #define csDecalManager_FACTORY_REGISTERED 
    csDecalManager_StaticInit csDecalManager_static_init__; 
  #endif
public:
 decal();
};
decal::decal() {}

}
