// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_dynavis[] =
"<?xml version=\"1.0\"?>"
"<!-- dynavis.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.culling.dynavis</name>"
"        <implementation>csDynaVis</implementation>"
"        <description>Dynamic Visibility System</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csDynaVis_FACTORY_REGISTER_DEFINED 
  #define csDynaVis_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csDynaVis) 
  #endif

class dynavis
{
SCF_REGISTER_STATIC_LIBRARY(dynavis,metainfo_dynavis)
  #ifndef csDynaVis_FACTORY_REGISTERED 
  #define csDynaVis_FACTORY_REGISTERED 
    csDynaVis_StaticInit csDynaVis_static_init__; 
  #endif
public:
 dynavis();
};
dynavis::dynavis() {}

}
