// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_dyndebug[] =
"<?xml version=\"1.0\"?>"
"<!-- dyndebug.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.dynamics.debug</name>"
"        <implementation>DebuggerManager</implementation>"
"        <description>Debugging of physical simulations</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef DebuggerManager_FACTORY_REGISTER_DEFINED 
  #define DebuggerManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(DebuggerManager) 
  #endif

class dyndebug
{
SCF_REGISTER_STATIC_LIBRARY(dyndebug,metainfo_dyndebug)
  #ifndef DebuggerManager_FACTORY_REGISTERED 
  #define DebuggerManager_FACTORY_REGISTERED 
    DebuggerManager_StaticInit DebuggerManager_static_init__; 
  #endif
public:
 dyndebug();
};
dyndebug::dyndebug() {}

}
