// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_debug[] =
"<?xml version=\"1.0\"?>"
"<!-- debug.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.animesh.animnode.debug</name>"
"        <implementation>DebugNodeManager</implementation>"
"        <description>Crystal Space debug animation nodes of an animated mesh</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef DebugNodeManager_FACTORY_REGISTER_DEFINED 
  #define DebugNodeManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(DebugNodeManager) 
  #endif

class debug
{
SCF_REGISTER_STATIC_LIBRARY(debug,metainfo_debug)
  #ifndef DebugNodeManager_FACTORY_REGISTERED 
  #define DebugNodeManager_FACTORY_REGISTERED 
    DebugNodeManager_StaticInit DebugNodeManager_static_init__; 
  #endif
public:
 debug();
};
debug::debug() {}

}
