// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_docpreproc[] =
"<?xml version=\"1.0\"?>"
"<!-- docpreproc.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.document.preprocessor</name>"
"        <implementation>DocumentPreprocessor</implementation>"
"        <description>Document preprocessor</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef DocumentPreprocessor_FACTORY_REGISTER_DEFINED 
  #define DocumentPreprocessor_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(DocumentPreprocessor) 
  #endif

class docpreproc
{
SCF_REGISTER_STATIC_LIBRARY(docpreproc,metainfo_docpreproc)
  #ifndef DocumentPreprocessor_FACTORY_REGISTERED 
  #define DocumentPreprocessor_FACTORY_REGISTERED 
    DocumentPreprocessor_StaticInit DocumentPreprocessor_static_init__; 
  #endif
public:
 docpreproc();
};
docpreproc::docpreproc() {}

}
