// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_dsplex[] =
"<?xml version=\"1.0\"?>"
"<!-- dsplex.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.documentsystem.multiplexer</name>"
"        <implementation>csDocumentSystemMultiplexer</implementation>"
"        <description>Document system multiplexer</description>"
"        <requires>"
"          <class>crystalspace.documentsystem.</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csDocumentSystemMultiplexer_FACTORY_REGISTER_DEFINED 
  #define csDocumentSystemMultiplexer_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csDocumentSystemMultiplexer) 
  #endif

class dsplex
{
SCF_REGISTER_STATIC_LIBRARY(dsplex,metainfo_dsplex)
  #ifndef csDocumentSystemMultiplexer_FACTORY_REGISTERED 
  #define csDocumentSystemMultiplexer_FACTORY_REGISTERED 
    csDocumentSystemMultiplexer_StaticInit csDocumentSystemMultiplexer_static_init__; 
  #endif
public:
 dsplex();
};
dsplex::dsplex() {}

}
