// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_engseq[] =
"<?xml version=\"1.0\"?>"
"<!-- engseq.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.utilities.sequence.engine</name>"
"        <implementation>csEngineSequenceManager</implementation>"
"        <description>Engine Sequence Manager</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csEngineSequenceManager_FACTORY_REGISTER_DEFINED 
  #define csEngineSequenceManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csEngineSequenceManager) 
  #endif

class engseq
{
SCF_REGISTER_STATIC_LIBRARY(engseq,metainfo_engseq)
  #ifndef csEngineSequenceManager_FACTORY_REGISTERED 
  #define csEngineSequenceManager_FACTORY_REGISTERED 
    csEngineSequenceManager_StaticInit csEngineSequenceManager_static_init__; 
  #endif
public:
 engseq();
};
engseq::engseq() {}

}
