// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_engine[] =
"<?xml version=\"1.0\"?>"
"<!-- engine.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.engine.3d</name>"
"        <implementation>csEngine</implementation>"
"        <description>Crystal Space 3D Engine</description>"
"        <requires>"
"          <class>crystalspace.kernel.</class>"
"          <class>crystalspace.graphics3d.</class>"
"          <class>crystalspace.graphic.image.io.</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csEngine_FACTORY_REGISTER_DEFINED 
  #define csEngine_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csEngine) 
  #endif

class engine
{
SCF_REGISTER_STATIC_LIBRARY(engine,metainfo_engine)
  #ifndef csEngine_FACTORY_REGISTERED 
  #define csEngine_FACTORY_REGISTERED 
    csEngine_StaticInit csEngine_static_init__; 
  #endif
public:
 engine();
};
engine::engine() {}

}
