// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_freefnt2[] =
"<?xml version=\"1.0\"?>"
"<!-- freefnt2.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.font.server.freetype2</name>"
"        <implementation>csFreeType2Server</implementation>"
"        <description>Crystal Space FreeType2 font server</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csFreeType2Server_FACTORY_REGISTER_DEFINED 
  #define csFreeType2Server_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csFreeType2Server) 
  #endif

class freefnt2
{
SCF_REGISTER_STATIC_LIBRARY(freefnt2,metainfo_freefnt2)
  #ifndef csFreeType2Server_FACTORY_REGISTERED 
  #define csFreeType2Server_FACTORY_REGISTERED 
    csFreeType2Server_StaticInit csFreeType2Server_static_init__; 
  #endif
public:
 freefnt2();
};
freefnt2::freefnt2() {}

}
