// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_fancycon[] =
"<?xml version=\"1.0\"?>"
"<!-- fancycon.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.console.output.fancy</name>"
"        <implementation>csFancyConsole</implementation>"
"        <description>Crystal Space fancy output console</description>"
"        <requires>"
"          <class>crystalspace.kernel.</class>"
"          <class>crystalspace.graphics3d.</class>"
"          <class>crystalspace.graphics2d.</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csFancyConsole_FACTORY_REGISTER_DEFINED 
  #define csFancyConsole_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csFancyConsole) 
  #endif

class fancycon
{
SCF_REGISTER_STATIC_LIBRARY(fancycon,metainfo_fancycon)
  #ifndef csFancyConsole_FACTORY_REGISTERED 
  #define csFancyConsole_FACTORY_REGISTERED 
    csFancyConsole_StaticInit csFancyConsole_static_init__; 
  #endif
public:
 fancycon();
};
fancycon::fancycon() {}

}
