// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_furmeshldr[] =
"<?xml version=\"1.0\"?>"
"<!-- furmeshldr.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.loader.factory.furmesh</name>"
"        <implementation>FurMeshFactoryLoader</implementation>"
"        <description>Crystal Space Fur Mesh Factory Loader</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.loader.furmesh</name>"
"        <implementation>FurMeshLoader</implementation>"
"        <description>Crystal Space Fur Mesh Mesh Loader</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.saver.factory.furmesh</name>"
"        <implementation>FurMeshFactorySaver</implementation>"
"        <description>Crystal Space Fur Mesh Factory Saver</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.saver.furmesh</name>"
"        <implementation>FurMeshSaver</implementation>"
"        <description>Crystal Space Fur Mesh Mesh Saver</description>"
"      </class>	  "
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef FurMeshFactoryLoader_FACTORY_REGISTER_DEFINED 
  #define FurMeshFactoryLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(FurMeshFactoryLoader) 
  #endif
  #ifndef FurMeshLoader_FACTORY_REGISTER_DEFINED 
  #define FurMeshLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(FurMeshLoader) 
  #endif
  #ifndef FurMeshFactorySaver_FACTORY_REGISTER_DEFINED 
  #define FurMeshFactorySaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(FurMeshFactorySaver) 
  #endif
  #ifndef FurMeshSaver_FACTORY_REGISTER_DEFINED 
  #define FurMeshSaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(FurMeshSaver) 
  #endif

class furmeshldr
{
SCF_REGISTER_STATIC_LIBRARY(furmeshldr,metainfo_furmeshldr)
  #ifndef FurMeshFactoryLoader_FACTORY_REGISTERED 
  #define FurMeshFactoryLoader_FACTORY_REGISTERED 
    FurMeshFactoryLoader_StaticInit FurMeshFactoryLoader_static_init__; 
  #endif
  #ifndef FurMeshLoader_FACTORY_REGISTERED 
  #define FurMeshLoader_FACTORY_REGISTERED 
    FurMeshLoader_StaticInit FurMeshLoader_static_init__; 
  #endif
  #ifndef FurMeshFactorySaver_FACTORY_REGISTERED 
  #define FurMeshFactorySaver_FACTORY_REGISTERED 
    FurMeshFactorySaver_StaticInit FurMeshFactorySaver_static_init__; 
  #endif
  #ifndef FurMeshSaver_FACTORY_REGISTERED 
  #define FurMeshSaver_FACTORY_REGISTERED 
    FurMeshSaver_StaticInit FurMeshSaver_static_init__; 
  #endif
public:
 furmeshldr();
};
furmeshldr::furmeshldr() {}

}
