// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_genmesh[] =
"<?xml version=\"1.0\"?>"
"<!-- genmesh.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.object.genmesh</name>"
"        <implementation>csGenmeshMeshObjectType</implementation>"
"        <description>Crystal Space General Mesh Type</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csGenmeshMeshObjectType_FACTORY_REGISTER_DEFINED 
  #define csGenmeshMeshObjectType_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csGenmeshMeshObjectType) 
  #endif

class genmesh
{
SCF_REGISTER_STATIC_LIBRARY(genmesh,metainfo_genmesh)
  #ifndef csGenmeshMeshObjectType_FACTORY_REGISTERED 
  #define csGenmeshMeshObjectType_FACTORY_REGISTERED 
    csGenmeshMeshObjectType_StaticInit csGenmeshMeshObjectType_static_init__; 
  #endif
public:
 genmesh();
};
genmesh::genmesh() {}

}
