// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_glshader_ps1[] =
"<?xml version=\"1.0\"?>"
"<!-- glshader_ps1.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.graphics3d.shader.glps1</name>"
"        <implementation>csGLShader_PS1</implementation>"
"		<description>OpenGL specific shaderprogram provider for Graphics3D which compiles PS 1.x programs into OpenGL equivalents</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csGLShader_PS1_FACTORY_REGISTER_DEFINED 
  #define csGLShader_PS1_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csGLShader_PS1) 
  #endif

class glshader_ps1
{
SCF_REGISTER_STATIC_LIBRARY(glshader_ps1,metainfo_glshader_ps1)
  #ifndef csGLShader_PS1_FACTORY_REGISTERED 
  #define csGLShader_PS1_FACTORY_REGISTERED 
    csGLShader_PS1_StaticInit csGLShader_PS1_static_init__; 
  #endif
public:
 glshader_ps1();
};
glshader_ps1::glshader_ps1() {}

}
