// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_glshader_arb[] =
"<?xml version=\"1.0\"?>"
"<!-- glshader_arb.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.graphics3d.shader.glarb</name>"
"        <implementation>csGLShader_ARB</implementation>"
"        <description>OpenGL specific shaderprogram provider for Graphics3D</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csGLShader_ARB_FACTORY_REGISTER_DEFINED 
  #define csGLShader_ARB_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csGLShader_ARB) 
  #endif

class glshader_arb
{
SCF_REGISTER_STATIC_LIBRARY(glshader_arb,metainfo_glshader_arb)
  #ifndef csGLShader_ARB_FACTORY_REGISTERED 
  #define csGLShader_ARB_FACTORY_REGISTERED 
    csGLShader_ARB_StaticInit csGLShader_ARB_static_init__; 
  #endif
public:
 glshader_arb();
};
glshader_arb::glshader_arb() {}

}
