// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_gmesh3ds[] =
"<?xml version=\"1.0\"?>"
"<!-- gmesh3ds.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.loader.factory.genmesh.3ds</name>"
"        <implementation>csGenmesh3DSFactoryLoader</implementation>"
"        <description>Crystal Space Genmesh 3DS Factory Loader</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csGenmesh3DSFactoryLoader_FACTORY_REGISTER_DEFINED 
  #define csGenmesh3DSFactoryLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csGenmesh3DSFactoryLoader) 
  #endif

class gmesh3ds
{
SCF_REGISTER_STATIC_LIBRARY(gmesh3ds,metainfo_gmesh3ds)
  #ifndef csGenmesh3DSFactoryLoader_FACTORY_REGISTERED 
  #define csGenmesh3DSFactoryLoader_FACTORY_REGISTERED 
    csGenmesh3DSFactoryLoader_StaticInit csGenmesh3DSFactoryLoader_static_init__; 
  #endif
public:
 gmesh3ds();
};
gmesh3ds::gmesh3ds() {}

}
