// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_glwin32[] =
"<?xml version=\"1.0\"?>"
"<!-- glwin32.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.graphics2d.glwin32</name>"
"        <implementation>csGraphics2DOpenGL</implementation>"
"        <description>Crystal Space 2D OpenGL graphics driver for Win32</description>"
"        <requires>"
"          <class>crystalspace.font.server.</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csGraphics2DOpenGL_FACTORY_REGISTER_DEFINED 
  #define csGraphics2DOpenGL_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csGraphics2DOpenGL) 
  #endif

class glwin32
{
SCF_REGISTER_STATIC_LIBRARY(glwin32,metainfo_glwin32)
  #ifndef csGraphics2DOpenGL_FACTORY_REGISTERED 
  #define csGraphics2DOpenGL_FACTORY_REGISTERED 
    csGraphics2DOpenGL_StaticInit csGraphics2DOpenGL_static_init__; 
  #endif
public:
 glwin32();
};
glwin32::glwin32() {}

}
