// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_gl3d[] =
"<?xml version=\"1.0\"?>"
"<!-- gl3d.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.graphics3d.opengl</name>"
"        <implementation>csGLGraphics3D</implementation>"
"        <description>OpenGL 3D graphics driver for Crystal Space</description>"
"        <requires>"
"          <class>crystalspace.font.server.</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csGLGraphics3D_FACTORY_REGISTER_DEFINED 
  #define csGLGraphics3D_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csGLGraphics3D) 
  #endif

class gl3d
{
SCF_REGISTER_STATIC_LIBRARY(gl3d,metainfo_gl3d)
  #ifndef csGLGraphics3D_FACTORY_REGISTERED 
  #define csGLGraphics3D_FACTORY_REGISTERED 
    csGLGraphics3D_StaticInit csGLGraphics3D_static_init__; 
  #endif
public:
 gl3d();
};
gl3d::gl3d() {}

}
