// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_ikphysical[] =
"<?xml version=\"1.0\"?>"
"<!-- ikphysical.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.animesh.animnode.ik.physical</name>"
"        <implementation>IKPhysicalManager</implementation>"
"        <description>Physics based implementation of the inverse kinematics animation node</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef IKPhysicalManager_FACTORY_REGISTER_DEFINED 
  #define IKPhysicalManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(IKPhysicalManager) 
  #endif

class ikphysical
{
SCF_REGISTER_STATIC_LIBRARY(ikphysical,metainfo_ikphysical)
  #ifndef IKPhysicalManager_FACTORY_REGISTERED 
  #define IKPhysicalManager_FACTORY_REGISTERED 
    IKPhysicalManager_StaticInit IKPhysicalManager_static_init__; 
  #endif
public:
 ikphysical();
};
ikphysical::ikphysical() {}

}
