// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_null2d[] =
"<?xml version=\"1.0\"?>"
"<!-- null2d.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.graphics2d.null</name>"
"        <implementation>csGraphics2DNull</implementation>"
"        <description>Null 2D graphics driver for Crystal Space</description>"
"        <requires>"
"          <class>crystalspace.font.server.</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csGraphics2DNull_FACTORY_REGISTER_DEFINED 
  #define csGraphics2DNull_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csGraphics2DNull) 
  #endif

class null2d
{
SCF_REGISTER_STATIC_LIBRARY(null2d,metainfo_null2d)
  #ifndef csGraphics2DNull_FACTORY_REGISTERED 
  #define csGraphics2DNull_FACTORY_REGISTERED 
    csGraphics2DNull_StaticInit csGraphics2DNull_static_init__; 
  #endif
public:
 null2d();
};
null2d::null2d() {}

}
