// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_null3d[] =
"<?xml version=\"1.0\"?>"
"<!-- null3d.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.graphics3d.null</name>"
"        <implementation>csNullGraphics3D</implementation>"
"        <description>Null 3D graphics driver for Crystal Space</description>"
"        <requires>"
"          <class>crystalspace.font.server.</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csNullGraphics3D_FACTORY_REGISTER_DEFINED 
  #define csNullGraphics3D_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csNullGraphics3D) 
  #endif

class null3d
{
SCF_REGISTER_STATIC_LIBRARY(null3d,metainfo_null3d)
  #ifndef csNullGraphics3D_FACTORY_REGISTERED 
  #define csNullGraphics3D_FACTORY_REGISTERED 
    csNullGraphics3D_StaticInit csNullGraphics3D_static_init__; 
  #endif
public:
 null3d();
};
null3d::null3d() {}

}
