// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_opcode2[] =
"<?xml version=\"1.0\"?>"
"<!-- opcode2.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.collisions.opcode2</name>"
"        <implementation>csOpcodeCollisionSystem</implementation>"
"        <description>OPCODE collision system</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csOpcodeCollisionSystem_FACTORY_REGISTER_DEFINED 
  #define csOpcodeCollisionSystem_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csOpcodeCollisionSystem) 
  #endif

class opcode2
{
SCF_REGISTER_STATIC_LIBRARY(opcode2,metainfo_opcode2)
  #ifndef csOpcodeCollisionSystem_FACTORY_REGISTERED 
  #define csOpcodeCollisionSystem_FACTORY_REGISTERED 
    csOpcodeCollisionSystem_StaticInit csOpcodeCollisionSystem_static_init__; 
  #endif
public:
 opcode2();
};
opcode2::opcode2() {}

}
