// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_odedynam[] =
"<?xml version=\"1.0\"?>"
"<!-- odedynam.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.dynamics.ode</name>"
"        <implementation>csODEDynamics</implementation>"
"        <description>ODE physics</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csODEDynamics_FACTORY_REGISTER_DEFINED 
  #define csODEDynamics_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csODEDynamics) 
  #endif

class odedynam
{
SCF_REGISTER_STATIC_LIBRARY(odedynam,metainfo_odedynam)
  #ifndef csODEDynamics_FACTORY_REGISTERED 
  #define csODEDynamics_FACTORY_REGISTERED 
    csODEDynamics_StaticInit csODEDynamics_static_init__; 
  #endif
public:
 odedynam();
};
odedynam::odedynam() {}

}
