// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_particles[] =
"<?xml version=\"1.0\"?>"
"<!-- particles.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.object.particles</name>"
"        <implementation>ParticlesMeshObjectType</implementation>"
"        <description>Crystal Space Particle System</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.object.particles.emitter</name>"
"        <implementation>ParticleEmitterFactory</implementation>"
"        <description>Crystal Space Particle System - Emitters</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.object.particles.effector</name>"
"        <implementation>ParticleEffectorFactory</implementation>"
"        <description>Crystal Space Particle System - Effectors</description>"
"      </class>      "
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef ParticlesMeshObjectType_FACTORY_REGISTER_DEFINED 
  #define ParticlesMeshObjectType_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(ParticlesMeshObjectType) 
  #endif
  #ifndef ParticleEmitterFactory_FACTORY_REGISTER_DEFINED 
  #define ParticleEmitterFactory_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(ParticleEmitterFactory) 
  #endif
  #ifndef ParticleEffectorFactory_FACTORY_REGISTER_DEFINED 
  #define ParticleEffectorFactory_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(ParticleEffectorFactory) 
  #endif

class particles
{
SCF_REGISTER_STATIC_LIBRARY(particles,metainfo_particles)
  #ifndef ParticlesMeshObjectType_FACTORY_REGISTERED 
  #define ParticlesMeshObjectType_FACTORY_REGISTERED 
    ParticlesMeshObjectType_StaticInit ParticlesMeshObjectType_static_init__; 
  #endif
  #ifndef ParticleEmitterFactory_FACTORY_REGISTERED 
  #define ParticleEmitterFactory_FACTORY_REGISTERED 
    ParticleEmitterFactory_StaticInit ParticleEmitterFactory_static_init__; 
  #endif
  #ifndef ParticleEffectorFactory_FACTORY_REGISTERED 
  #define ParticleEffectorFactory_FACTORY_REGISTERED 
    ParticleEffectorFactory_StaticInit ParticleEffectorFactory_static_init__; 
  #endif
public:
 particles();
};
particles::particles() {}

}
