// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_physldr2[] =
"<?xml version=\"1.0\"?>"
"<!-- physldr2.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.physics.loader2</name>"
"        <implementation>csPhysicsLoader2</implementation>"
"        <description>Crystal Space physics loader</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csPhysicsLoader2_FACTORY_REGISTER_DEFINED 
  #define csPhysicsLoader2_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csPhysicsLoader2) 
  #endif

class physldr2
{
SCF_REGISTER_STATIC_LIBRARY(physldr2,metainfo_physldr2)
  #ifndef csPhysicsLoader2_FACTORY_REGISTERED 
  #define csPhysicsLoader2_FACTORY_REGISTERED 
    csPhysicsLoader2_StaticInit csPhysicsLoader2_static_init__; 
  #endif
public:
 physldr2();
};
physldr2::physldr2() {}

}
