// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_physldr[] =
"<?xml version=\"1.0\"?>"
"<!-- physldr.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.dynamics.loader</name>"
"        <implementation>csPhysicsLoader</implementation>"
"        <description>Crystal Space dynamics loader</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csPhysicsLoader_FACTORY_REGISTER_DEFINED 
  #define csPhysicsLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csPhysicsLoader) 
  #endif

class physldr
{
SCF_REGISTER_STATIC_LIBRARY(physldr,metainfo_physldr)
  #ifndef csPhysicsLoader_FACTORY_REGISTERED 
  #define csPhysicsLoader_FACTORY_REGISTERED 
    csPhysicsLoader_StaticInit csPhysicsLoader_static_init__; 
  #endif
public:
 physldr();
};
physldr::physldr() {}

}
