// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_reporter[] =
"<?xml version=\"1.0\"?>"
"<!-- reporter.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.utilities.reporter</name>"
"        <implementation>csReporter</implementation>"
"        <description>Reporting utility</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csReporter_FACTORY_REGISTER_DEFINED 
  #define csReporter_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csReporter) 
  #endif

class reporter
{
SCF_REGISTER_STATIC_LIBRARY(reporter,metainfo_reporter)
  #ifndef csReporter_FACTORY_REGISTERED 
  #define csReporter_FACTORY_REGISTERED 
    csReporter_StaticInit csReporter_static_init__; 
  #endif
public:
 reporter();
};
reporter::reporter() {}

}
