// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_rm_null[] =
"<?xml version=\"1.0\"?>"
"<!-- rm_null.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.rendermanager.null</name>"
"        <implementation>RMNull</implementation>"
"        <description>Null Rendermanager (renders nothing)</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef RMNull_FACTORY_REGISTER_DEFINED 
  #define RMNull_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(RMNull) 
  #endif

class rm_null
{
SCF_REGISTER_STATIC_LIBRARY(rm_null,metainfo_rm_null)
  #ifndef RMNull_FACTORY_REGISTERED 
  #define RMNull_FACTORY_REGISTERED 
    RMNull_StaticInit RMNull_static_init__; 
  #endif
public:
 rm_null();
};
rm_null::rm_null() {}

}
