// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_rm_rlcompat[] =
"<?xml version=\"1.0\"?>"
"<!-- rm_rlcompat.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.rendermanager.rlcompat</name>"
"        <implementation>RMCompat</implementation>"
"        <description>Rendermanager for RL compatibility</description>"
"        <requires>"
"          <class>crystalspace.engine.</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef RMCompat_FACTORY_REGISTER_DEFINED 
  #define RMCompat_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(RMCompat) 
  #endif

class rm_rlcompat
{
SCF_REGISTER_STATIC_LIBRARY(rm_rlcompat,metainfo_rm_rlcompat)
  #ifndef RMCompat_FACTORY_REGISTERED 
  #define RMCompat_FACTORY_REGISTERED 
    RMCompat_StaticInit RMCompat_static_init__; 
  #endif
public:
 rm_rlcompat();
};
rm_rlcompat::rm_rlcompat() {}

}
