// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_rm_shadow_pssm[] =
"<?xml version=\"1.0\"?>"
"<!-- rm_shadow_pssm.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.rendermanager.shadow_pssm</name>"
"        <implementation>RMShadowedPSSM</implementation>"
"        <description>Rendermanager (PSSM shadows)</description>"
"        <requires>"
"          <class>crystalspace.engine.</class>"
"          <class>crystalspace.graphics3d.</class>         "
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef RMShadowedPSSM_FACTORY_REGISTER_DEFINED 
  #define RMShadowedPSSM_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(RMShadowedPSSM) 
  #endif

class rm_shadow_pssm
{
SCF_REGISTER_STATIC_LIBRARY(rm_shadow_pssm,metainfo_rm_shadow_pssm)
  #ifndef RMShadowedPSSM_FACTORY_REGISTERED 
  #define RMShadowedPSSM_FACTORY_REGISTERED 
    RMShadowedPSSM_StaticInit RMShadowedPSSM_static_init__; 
  #endif
public:
 rm_shadow_pssm();
};
rm_shadow_pssm::rm_shadow_pssm() {}

}
