// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_retarget[] =
"<?xml version=\"1.0\"?>"
"<!-- retarget.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.animesh.animnode.retarget</name>"
"        <implementation>RetargetNodeManager</implementation>"
"        <description>Crystal Space Retarget animation node of an animated mesh</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef RetargetNodeManager_FACTORY_REGISTER_DEFINED 
  #define RetargetNodeManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(RetargetNodeManager) 
  #endif

class retarget
{
SCF_REGISTER_STATIC_LIBRARY(retarget,metainfo_retarget)
  #ifndef RetargetNodeManager_FACTORY_REGISTERED 
  #define RetargetNodeManager_FACTORY_REGISTERED 
    RetargetNodeManager_StaticInit RetargetNodeManager_static_init__; 
  #endif
public:
 retarget();
};
retarget::retarget() {}

}
