// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_rm_deferred[] =
"<?xml version=\"1.0\"?>"
"<!-- rm_deferred.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.rendermanager.deferred</name>"
"        <implementation>RMDeferred</implementation>"
"        <description>Rendermanager (deferred)</description>"
"        <requires>"
"          <class>crystalspace.engine.</class>"
"          <class>crystalspace.graphics3d.</class>         "
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef RMDeferred_FACTORY_REGISTER_DEFINED 
  #define RMDeferred_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(RMDeferred) 
  #endif

class rm_deferred
{
SCF_REGISTER_STATIC_LIBRARY(rm_deferred,metainfo_rm_deferred)
  #ifndef RMDeferred_FACTORY_REGISTERED 
  #define RMDeferred_FACTORY_REGISTERED 
    RMDeferred_StaticInit RMDeferred_static_init__; 
  #endif
public:
 rm_deferred();
};
rm_deferred::rm_deferred() {}

}
