// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_sndsyswav[] =
"<?xml version=\"1.0\"?>"
"<!-- sndsyswav.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.sndsys.element.wav</name>"
"        <implementation>SndSysWavLoader</implementation>"
"        <description>Waveform PCM Sound System Element</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
""
;
  #ifndef SndSysWavLoader_FACTORY_REGISTER_DEFINED 
  #define SndSysWavLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(SndSysWavLoader) 
  #endif

class sndsyswav
{
SCF_REGISTER_STATIC_LIBRARY(sndsyswav,metainfo_sndsyswav)
  #ifndef SndSysWavLoader_FACTORY_REGISTERED 
  #define SndSysWavLoader_FACTORY_REGISTERED 
    SndSysWavLoader_StaticInit SndSysWavLoader_static_init__; 
  #endif
public:
 sndsyswav();
};
sndsyswav::sndsyswav() {}

}
