// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_slcombiner[] =
"<?xml version=\"1.0\"?>"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.graphics3d.shader.combiner.glcg</name>"
"        <implementation>ShaderCombinerLoaderCg</implementation>"
"        <description>Cg-specific combiner for shader snippets</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.graphics3d.shader.combiner.glsl</name>"
"        <implementation>ShaderCombinerLoaderGLSL</implementation>"
"        <description>GLSL-specific combiner for shader snippets</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef ShaderCombinerLoaderCg_FACTORY_REGISTER_DEFINED 
  #define ShaderCombinerLoaderCg_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(ShaderCombinerLoaderCg) 
  #endif
  #ifndef ShaderCombinerLoaderGLSL_FACTORY_REGISTER_DEFINED 
  #define ShaderCombinerLoaderGLSL_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(ShaderCombinerLoaderGLSL) 
  #endif

class slcombiner
{
SCF_REGISTER_STATIC_LIBRARY(slcombiner,metainfo_slcombiner)
  #ifndef ShaderCombinerLoaderCg_FACTORY_REGISTERED 
  #define ShaderCombinerLoaderCg_FACTORY_REGISTERED 
    ShaderCombinerLoaderCg_StaticInit ShaderCombinerLoaderCg_static_init__; 
  #endif
  #ifndef ShaderCombinerLoaderGLSL_FACTORY_REGISTERED 
  #define ShaderCombinerLoaderGLSL_FACTORY_REGISTERED 
    ShaderCombinerLoaderGLSL_StaticInit ShaderCombinerLoaderGLSL_static_init__; 
  #endif
public:
 slcombiner();
};
slcombiner::slcombiner() {}

}
