// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_sndmanager[] =
"<?xml version=\"1.0\"?>"
"<!-- sndmanager.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.sndsys.manager</name>"
"        <implementation>csSndSysManager</implementation>"
"        <description>Sound Manager</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSndSysManager_FACTORY_REGISTER_DEFINED 
  #define csSndSysManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSndSysManager) 
  #endif

class sndmanager
{
SCF_REGISTER_STATIC_LIBRARY(sndmanager,metainfo_sndmanager)
  #ifndef csSndSysManager_FACTORY_REGISTERED 
  #define csSndSysManager_FACTORY_REGISTERED 
    csSndSysManager_StaticInit csSndSysManager_static_init__; 
  #endif
public:
 sndmanager();
};
sndmanager::sndmanager() {}

}
