// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_sequence[] =
"<?xml version=\"1.0\"?>"
"<!-- sequence.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.utilities.sequence</name>"
"        <implementation>csSequenceManager</implementation>"
"        <description>Sequence Manager</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSequenceManager_FACTORY_REGISTER_DEFINED 
  #define csSequenceManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSequenceManager) 
  #endif

class sequence
{
SCF_REGISTER_STATIC_LIBRARY(sequence,metainfo_sequence)
  #ifndef csSequenceManager_FACTORY_REGISTERED 
  #define csSequenceManager_FACTORY_REGISTERED 
    csSequenceManager_StaticInit csSequenceManager_static_init__; 
  #endif
public:
 sequence();
};
sequence::sequence() {}

}
