// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_splitmorph[] =
"<?xml version=\"1.0\"?>"
"<!-- splitmorph.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.loader.factory.animesh.splitmorph</name>"
"        <implementation>SplitMorphLoader</implementation>"
"        <description>Loader of animated mesh with morph targets split in several files</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef SplitMorphLoader_FACTORY_REGISTER_DEFINED 
  #define SplitMorphLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(SplitMorphLoader) 
  #endif

class splitmorph
{
SCF_REGISTER_STATIC_LIBRARY(splitmorph,metainfo_splitmorph)
  #ifndef SplitMorphLoader_FACTORY_REGISTERED 
  #define SplitMorphLoader_FACTORY_REGISTERED 
    SplitMorphLoader_StaticInit SplitMorphLoader_static_init__; 
  #endif
public:
 splitmorph();
};
splitmorph::splitmorph() {}

}
