// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_spr3dldr[] =
"<?xml version=\"1.0\"?>"
"<!-- spr3dldr.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.loader.factory.sprite.3d</name>"
"        <implementation>csSprite3DFactoryLoader</implementation>"
"        <description>Crystal Space Sprite3D Mesh Factory Loader</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.loader.sprite.3d</name>"
"        <implementation>csSprite3DLoader</implementation>"
"        <description>Crystal Space Sprite3D Mesh Loader</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.saver.factory.sprite.3d</name>"
"        <implementation>csSprite3DFactorySaver</implementation>"
"        <description>Crystal Space Sprite3D Mesh Factory Saver</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.saver.sprite.3d</name>"
"        <implementation>csSprite3DSaver</implementation>"
"        <description>Crystal Space Sprite3D Mesh Saver</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSprite3DFactoryLoader_FACTORY_REGISTER_DEFINED 
  #define csSprite3DFactoryLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSprite3DFactoryLoader) 
  #endif
  #ifndef csSprite3DLoader_FACTORY_REGISTER_DEFINED 
  #define csSprite3DLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSprite3DLoader) 
  #endif
  #ifndef csSprite3DFactorySaver_FACTORY_REGISTER_DEFINED 
  #define csSprite3DFactorySaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSprite3DFactorySaver) 
  #endif
  #ifndef csSprite3DSaver_FACTORY_REGISTER_DEFINED 
  #define csSprite3DSaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSprite3DSaver) 
  #endif

class spr3dldr
{
SCF_REGISTER_STATIC_LIBRARY(spr3dldr,metainfo_spr3dldr)
  #ifndef csSprite3DFactoryLoader_FACTORY_REGISTERED 
  #define csSprite3DFactoryLoader_FACTORY_REGISTERED 
    csSprite3DFactoryLoader_StaticInit csSprite3DFactoryLoader_static_init__; 
  #endif
  #ifndef csSprite3DLoader_FACTORY_REGISTERED 
  #define csSprite3DLoader_FACTORY_REGISTERED 
    csSprite3DLoader_StaticInit csSprite3DLoader_static_init__; 
  #endif
  #ifndef csSprite3DFactorySaver_FACTORY_REGISTERED 
  #define csSprite3DFactorySaver_FACTORY_REGISTERED 
    csSprite3DFactorySaver_StaticInit csSprite3DFactorySaver_static_init__; 
  #endif
  #ifndef csSprite3DSaver_FACTORY_REGISTERED 
  #define csSprite3DSaver_FACTORY_REGISTERED 
    csSprite3DSaver_StaticInit csSprite3DSaver_static_init__; 
  #endif
public:
 spr3dldr();
};
spr3dldr::spr3dldr() {}

}
