// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_skeleton2ldr[] =
"<?xml version=\"1.0\"?>"
"<!-- skeleton2ldr.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.skeletalanimation.loader</name>"
"        <implementation>SkeletonLoader</implementation>"
"        <description>Crystal Space Skeletal animation loader plugin</description>"
"      </class>    "
"      <class>"
"        <name>crystalspace.skeletalanimation.saver</name>"
"        <implementation>SkeletonSaver</implementation>"
"        <description>Crystal Space Skeletal animation saver plugin</description>"
"      </class>    "
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef SkeletonLoader_FACTORY_REGISTER_DEFINED 
  #define SkeletonLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(SkeletonLoader) 
  #endif
  #ifndef SkeletonSaver_FACTORY_REGISTER_DEFINED 
  #define SkeletonSaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(SkeletonSaver) 
  #endif

class skeleton2ldr
{
SCF_REGISTER_STATIC_LIBRARY(skeleton2ldr,metainfo_skeleton2ldr)
  #ifndef SkeletonLoader_FACTORY_REGISTERED 
  #define SkeletonLoader_FACTORY_REGISTERED 
    SkeletonLoader_StaticInit SkeletonLoader_static_init__; 
  #endif
  #ifndef SkeletonSaver_FACTORY_REGISTERED 
  #define SkeletonSaver_FACTORY_REGISTERED 
    SkeletonSaver_StaticInit SkeletonSaver_static_init__; 
  #endif
public:
 skeleton2ldr();
};
skeleton2ldr::skeleton2ldr() {}

}
