// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_spr3md2[] =
"<?xml version=\"1.0\"?>"
"<!-- spr3dbin.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.loader.factory.sprite.3d.md2</name>"
"        <implementation>csSprite3DMD2FactoryLoader</implementation>"
"        <description>Crystal Space Sprite3D MD2 Mesh Factory Loader</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSprite3DMD2FactoryLoader_FACTORY_REGISTER_DEFINED 
  #define csSprite3DMD2FactoryLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSprite3DMD2FactoryLoader) 
  #endif

class spr3md2
{
SCF_REGISTER_STATIC_LIBRARY(spr3md2,metainfo_spr3md2)
  #ifndef csSprite3DMD2FactoryLoader_FACTORY_REGISTERED 
  #define csSprite3DMD2FactoryLoader_FACTORY_REGISTERED 
    csSprite3DMD2FactoryLoader_StaticInit csSprite3DMD2FactoryLoader_static_init__; 
  #endif
public:
 spr3md2();
};
spr3md2::spr3md2() {}

}
