// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_stdrep[] =
"<?xml version=\"1.0\"?>"
"<!-- stdrep.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.utilities.stdrep</name>"
"        <implementation>csReporterListener</implementation>"
"        <description>Standard Reporter Listener</description>"
"        <requires>"
"          <class>crystalspace.utilities.reporter</class>"
"          <class>crystalspace.console.output.</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csReporterListener_FACTORY_REGISTER_DEFINED 
  #define csReporterListener_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csReporterListener) 
  #endif

class stdrep
{
SCF_REGISTER_STATIC_LIBRARY(stdrep,metainfo_stdrep)
  #ifndef csReporterListener_FACTORY_REGISTERED 
  #define csReporterListener_FACTORY_REGISTERED 
    csReporterListener_StaticInit csReporterListener_static_init__; 
  #endif
public:
 stdrep();
};
stdrep::stdrep() {}

}
