// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_sndsysogg[] =
"<?xml version=\"1.0\"?>"
"<!-- sndsysogg.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.sndsys.element.ogg</name>"
"        <implementation>SndSysOggLoader</implementation>"
"        <description>Ogg Vorbis Sound System Element</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
""
;
  #ifndef SndSysOggLoader_FACTORY_REGISTER_DEFINED 
  #define SndSysOggLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(SndSysOggLoader) 
  #endif

class sndsysogg
{
SCF_REGISTER_STATIC_LIBRARY(sndsysogg,metainfo_sndsysogg)
  #ifndef SndSysOggLoader_FACTORY_REGISTERED 
  #define SndSysOggLoader_FACTORY_REGISTERED 
    SndSysOggLoader_StaticInit SndSysOggLoader_static_init__; 
  #endif
public:
 sndsysogg();
};
sndsysogg::sndsysogg() {}

}
