// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_spr3dbin[] =
"<?xml version=\"1.0\"?>"
"<!-- spr3dbin.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.loader.factory.sprite.3d.binary</name>"
"        <implementation>csSprite3DBinFactoryLoader</implementation>"
"        <description>Crystal Space Sprite3DBin Mesh Factory Loader</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.saver.factory.sprite.3d.binary</name>"
"        <implementation>csSprite3DBinFactorySaver</implementation>"
"        <description>Crystal Space Sprite3DBin Mesh Factory Saver</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSprite3DBinFactoryLoader_FACTORY_REGISTER_DEFINED 
  #define csSprite3DBinFactoryLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSprite3DBinFactoryLoader) 
  #endif
  #ifndef csSprite3DBinFactorySaver_FACTORY_REGISTER_DEFINED 
  #define csSprite3DBinFactorySaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSprite3DBinFactorySaver) 
  #endif

class spr3dbin
{
SCF_REGISTER_STATIC_LIBRARY(spr3dbin,metainfo_spr3dbin)
  #ifndef csSprite3DBinFactoryLoader_FACTORY_REGISTERED 
  #define csSprite3DBinFactoryLoader_FACTORY_REGISTERED 
    csSprite3DBinFactoryLoader_StaticInit csSprite3DBinFactoryLoader_static_init__; 
  #endif
  #ifndef csSprite3DBinFactorySaver_FACTORY_REGISTERED 
  #define csSprite3DBinFactorySaver_FACTORY_REGISTERED 
    csSprite3DBinFactorySaver_StaticInit csSprite3DBinFactorySaver_static_init__; 
  #endif
public:
 spr3dbin();
};
spr3dbin::spr3dbin() {}

}
