// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_sprcal3d[] =
"<?xml version=\"1.0\"?>"
"<!-- spr3d.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.object.sprite.cal3d</name>"
"        <implementation>csSpriteCal3DMeshObjectType</implementation>"
"        <description>Crystal Space SpriteCal3D Mesh Type</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSpriteCal3DMeshObjectType_FACTORY_REGISTER_DEFINED 
  #define csSpriteCal3DMeshObjectType_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSpriteCal3DMeshObjectType) 
  #endif

class sprcal3d
{
SCF_REGISTER_STATIC_LIBRARY(sprcal3d,metainfo_sprcal3d)
  #ifndef csSpriteCal3DMeshObjectType_FACTORY_REGISTERED 
  #define csSpriteCal3DMeshObjectType_FACTORY_REGISTERED 
    csSpriteCal3DMeshObjectType_StaticInit csSpriteCal3DMeshObjectType_static_init__; 
  #endif
public:
 sprcal3d();
};
sprcal3d::sprcal3d() {}

}
