// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_sndsyswin[] =
"<?xml version=\"1.0\"?>"
"<!-- sndsyswin.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.sndsys.software.driver.directsound</name>"
"        <implementation>SndSysDriverDirectSound</implementation>"
"        <description>Sound System DirectSound Software Driver</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
""
;
  #ifndef SndSysDriverDirectSound_FACTORY_REGISTER_DEFINED 
  #define SndSysDriverDirectSound_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(SndSysDriverDirectSound) 
  #endif

class sndsyswin
{
SCF_REGISTER_STATIC_LIBRARY(sndsyswin,metainfo_sndsyswin)
  #ifndef SndSysDriverDirectSound_FACTORY_REGISTERED 
  #define SndSysDriverDirectSound_FACTORY_REGISTERED 
    SndSysDriverDirectSound_StaticInit SndSysDriverDirectSound_static_init__; 
  #endif
public:
 sndsyswin();
};
sndsyswin::sndsyswin() {}

}
