// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_sndsyssoft[] =
"<?xml version=\"1.0\"?>"
"<!-- sndsyssoft.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.sndsys.renderer.software</name>"
"        <implementation>csSndSysRendererSoftware</implementation>"
"        <description>Sound System Software Renderer</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
""
;
  #ifndef csSndSysRendererSoftware_FACTORY_REGISTER_DEFINED 
  #define csSndSysRendererSoftware_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSndSysRendererSoftware) 
  #endif

class sndsyssoft
{
SCF_REGISTER_STATIC_LIBRARY(sndsyssoft,metainfo_sndsyssoft)
  #ifndef csSndSysRendererSoftware_FACTORY_REGISTERED 
  #define csSndSysRendererSoftware_FACTORY_REGISTERED 
    csSndSysRendererSoftware_StaticInit csSndSysRendererSoftware_static_init__; 
  #endif
public:
 sndsyssoft();
};
sndsyssoft::sndsyssoft() {}

}
