// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_sndsysnull[] =
"<?xml version=\"1.0\"?>"
"<!-- sndsysnull.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.sndsys.software.driver.null</name>"
"        <implementation>SndSysDriverNull</implementation>"
"        <description>Sound System Null (no output) Software Driver</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
""
;
  #ifndef SndSysDriverNull_FACTORY_REGISTER_DEFINED 
  #define SndSysDriverNull_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(SndSysDriverNull) 
  #endif

class sndsysnull
{
SCF_REGISTER_STATIC_LIBRARY(sndsysnull,metainfo_sndsysnull)
  #ifndef SndSysDriverNull_FACTORY_REGISTERED 
  #define SndSysDriverNull_FACTORY_REGISTERED 
    SndSysDriverNull_StaticInit SndSysDriverNull_static_init__; 
  #endif
public:
 sndsysnull();
};
sndsysnull::sndsysnull() {}

}
