// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_simpleformer[] =
"<?xml version=\"1.0\"?>"
"<!-- simpleformer.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.terraformer.simple</name>"
"        <implementation>csSimpleFormer</implementation>"
"        <description>Simple terrain formation generator</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSimpleFormer_FACTORY_REGISTER_DEFINED 
  #define csSimpleFormer_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSimpleFormer) 
  #endif

class simpleformer
{
SCF_REGISTER_STATIC_LIBRARY(simpleformer,metainfo_simpleformer)
  #ifndef csSimpleFormer_FACTORY_REGISTERED 
  #define csSimpleFormer_FACTORY_REGISTERED 
    csSimpleFormer_StaticInit csSimpleFormer_static_init__; 
  #endif
public:
 simpleformer();
};
simpleformer::simpleformer() {}

}
