// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_texthud[] =
"<?xml version=\"1.0\"?>"
"<!-- texthud.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.utilities.texthud</name>"
"        <implementation>TextHUDManager</implementation>"
"        <description>Text-based HUD manager</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef TextHUDManager_FACTORY_REGISTER_DEFINED 
  #define TextHUDManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(TextHUDManager) 
  #endif

class texthud
{
SCF_REGISTER_STATIC_LIBRARY(texthud,metainfo_texthud)
  #ifndef TextHUDManager_FACTORY_REGISTERED 
  #define TextHUDManager_FACTORY_REGISTERED 
    TextHUDManager_StaticInit TextHUDManager_static_init__; 
  #endif
public:
 texthud();
};
texthud::texthud() {}

}
