// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_xmlread[] =
"<?xml version=\"1.0\"?>"
"<!-- xmlread.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.documentsystem.xmlread</name>"
"        <implementation>csXmlReadXMLPlugin</implementation>"
"        <description>Crystal Space XmlRead document system</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csXmlReadXMLPlugin_FACTORY_REGISTER_DEFINED 
  #define csXmlReadXMLPlugin_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csXmlReadXMLPlugin) 
  #endif

class xmlread
{
SCF_REGISTER_STATIC_LIBRARY(xmlread,metainfo_xmlread)
  #ifndef csXmlReadXMLPlugin_FACTORY_REGISTERED 
  #define csXmlReadXMLPlugin_FACTORY_REGISTERED 
    csXmlReadXMLPlugin_StaticInit csXmlReadXMLPlugin_static_init__; 
  #endif
public:
 xmlread();
};
xmlread::xmlread() {}

}
