// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_xmlshader[] =
"<?xml version=\"1.0\"?>"
"<!-- xmlshader.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.graphics3d.shadercompiler.xmlshader</name>"
"        <implementation>csXMLShaderCompiler</implementation>"
"        <description>XML-format shader compiler</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csXMLShaderCompiler_FACTORY_REGISTER_DEFINED 
  #define csXMLShaderCompiler_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csXMLShaderCompiler) 
  #endif

class xmlshader
{
SCF_REGISTER_STATIC_LIBRARY(xmlshader,metainfo_xmlshader)
  #ifndef csXMLShaderCompiler_FACTORY_REGISTERED 
  #define csXMLShaderCompiler_FACTORY_REGISTERED 
    csXMLShaderCompiler_StaticInit csXMLShaderCompiler_static_init__; 
  #endif
public:
 xmlshader();
};
xmlshader::xmlshader() {}

}
